name: Build and Push Docker Images

on:
  push: 
    branches: 
        - master
  workflow_dispatch:      # 允许手动触发

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build image & push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1️、获取仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️、设置 Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️、登录 GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}       # 当前 GitHub 用户
          password: ${{ secrets.GITHUB_TOKEN }} # 自动生成的 token

      # 4️、构建并推送镜像
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag || 'latest' }}